/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AssetGate {
    /**
    * True when the given wallet owns any token from a given contract.
    */
    'hasContract': boolean;
    /**
    * Only true when the given wallet owns a particular token from a given contract.
    */
    'hasToken': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasContract",
            "baseName": "hasContract",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasToken",
            "baseName": "hasToken",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetGate.attributeTypeMap;
    }

    public constructor() {
    }
}

