/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AutoSuggestion {
    /**
    * A URL-encoded string that can be used in conjunction with the search endpoint
    */
    'query'?: string;
    /**
    * The suggestion result's title fully spelled out
    */
    'title'?: string;
    /**
    * The type of result the suggestion is based on, e.g. Bored Ape Yacht Club would be a collection.
    */
    'type'?: AutoSuggestionTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AutoSuggestionTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutoSuggestion.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AutoSuggestionTypeEnum = "query" | "collection" | "wallet" | "token" ;

