/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MediaPreview } from './MediaPreview';
import { HttpFile } from '../http/http';

export class AutoSuggestion {
    /**
    * A hex string representing the address of the entity
    */
    'address'?: string;
    /**
    * Media metadata corresponding to the suggestion
    */
    'previews'?: Array<MediaPreview>;
    /**
    * A URL-encoded string that can be used in conjunction with the search endpoint
    */
    'query'?: string;
    /**
    * The suggestion result's title fully spelled out
    */
    'title'?: string;
    /**
    * For tokens, the unique identifier within the contract
    */
    'tokenID'?: string;
    /**
    * The type of result the suggestion is based on, e.g. Bored Ape Yacht Club would be a collection.
    */
    'type'?: AutoSuggestionTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "previews",
            "baseName": "previews",
            "type": "Array<MediaPreview>",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenID",
            "baseName": "tokenID",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AutoSuggestionTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutoSuggestion.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AutoSuggestionTypeEnum = "query" | "collection" | "wallet" | "token" ;

