/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyInfo } from './CurrencyInfo';
import { MediaPreview } from './MediaPreview';
import { HttpFile } from '../http/http';

export class ERC20Metadata {
    /**
    * ERC-20 contract address.
    */
    'contractAddress'?: string;
    'currentPrice'?: CurrencyInfo;
    /**
    * The number of decimals the token uses
    */
    'decimals'?: number;
    /**
    * The name of the erc-20 token
    */
    'name'?: string;
    /**
    * The symbol of the erc-20 token
    */
    'symbol'?: string;
    /**
    * Logo images associated with the token for a given currency.
    */
    'symbolLogos'?: Array<MediaPreview>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contractAddress",
            "baseName": "contractAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentPrice",
            "baseName": "currentPrice",
            "type": "CurrencyInfo",
            "format": ""
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "symbolLogos",
            "baseName": "symbolLogos",
            "type": "Array<MediaPreview>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ERC20Metadata.attributeTypeMap;
    }

    public constructor() {
    }
}

