/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.18.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MediaVersion {
    /**
    * If a video, length of video in ISO 8601 duration format.
    */
    'duration'?: string;
    'format'?: string;
    'height'?: number;
    'kind'?: MediaVersionKindEnum;
    'numBytes'?: number;
    'width'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "MediaVersionKindEnum",
            "format": ""
        },
        {
            "name": "numBytes",
            "baseName": "numBytes",
            "type": "number",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MediaVersion.attributeTypeMap;
    }

    public constructor() {
    }
}


export type MediaVersionKindEnum = "video" | "image" | "raw" | "audio" ;

