/* tslint:disable */
/* eslint-disable */
/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * The version of the OpenAPI document: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaPreview
 */
export interface MediaPreview {
    /**
     * URI for the image asset.
     * @type {string}
     * @memberof MediaPreview
     */
    uRI?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaPreview
     */
    kind?: MediaPreviewKindEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaPreview
     */
    format?: string;
    /**
     * The image's approximate height in pixels.
     * @type {number}
     * @memberof MediaPreview
     */
    height?: number;
    /**
     * The image's approximate width in pixels.
     * @type {number}
     * @memberof MediaPreview
     */
    width?: number;
    /**
     * If a video, length of video in ISO 8601 duration format.
     * @type {string}
     * @memberof MediaPreview
     */
    duration?: string;
}


/**
 * @export
 */
export const MediaPreviewKindEnum = {
    Video: 'video',
    Image: 'image',
    Raw: 'raw',
    Audio: 'audio'
} as const;
export type MediaPreviewKindEnum = typeof MediaPreviewKindEnum[keyof typeof MediaPreviewKindEnum];


/**
 * Check if a given object implements the MediaPreview interface.
 */
export function instanceOfMediaPreview(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaPreviewFromJSON(json: any): MediaPreview {
    return MediaPreviewFromJSONTyped(json, false);
}

export function MediaPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaPreview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uRI': !exists(json, 'URI') ? undefined : json['URI'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'format': !exists(json, 'format') ? undefined : json['format'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
    };
}

export function MediaPreviewToJSON(value?: MediaPreview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'URI': value.uRI,
        'kind': value.kind,
        'format': value.format,
        'height': value.height,
        'width': value.width,
        'duration': value.duration,
    };
}

