/* tslint:disable */
/* eslint-disable */
/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * The version of the OpenAPI document: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaVersion
 */
export interface MediaVersion {
    /**
     * 
     * @type {string}
     * @memberof MediaVersion
     */
    kind?: MediaVersionKindEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaVersion
     */
    format?: string;
    /**
     * 
     * @type {number}
     * @memberof MediaVersion
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof MediaVersion
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof MediaVersion
     */
    numBytes?: number;
    /**
     * If a video, length of video in ISO 8601 duration format.
     * @type {string}
     * @memberof MediaVersion
     */
    duration?: string;
}


/**
 * @export
 */
export const MediaVersionKindEnum = {
    Video: 'video',
    Image: 'image',
    Raw: 'raw',
    Audio: 'audio'
} as const;
export type MediaVersionKindEnum = typeof MediaVersionKindEnum[keyof typeof MediaVersionKindEnum];


/**
 * Check if a given object implements the MediaVersion interface.
 */
export function instanceOfMediaVersion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaVersionFromJSON(json: any): MediaVersion {
    return MediaVersionFromJSONTyped(json, false);
}

export function MediaVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'format': !exists(json, 'format') ? undefined : json['format'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'numBytes': !exists(json, 'numBytes') ? undefined : json['numBytes'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
    };
}

export function MediaVersionToJSON(value?: MediaVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'format': value.format,
        'width': value.width,
        'height': value.height,
        'numBytes': value.numBytes,
        'duration': value.duration,
    };
}

