/* tslint:disable */
/* eslint-disable */
/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * The version of the OpenAPI document: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaVersion } from './MediaVersion';
import {
    MediaVersionFromJSON,
    MediaVersionFromJSONTyped,
    MediaVersionToJSON,
} from './MediaVersion';

/**
 * 
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    key: string;
    /**
     * URI for the image asset.
     * @type {string}
     * @memberof Media
     */
    uRI?: string;
    /**
     * 
     * @type {Array<MediaVersion>}
     * @memberof Media
     */
    version?: Array<MediaVersion>;
}

/**
 * Check if a given object implements the Media interface.
 */
export function instanceOfMedia(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function MediaFromJSON(json: any): Media {
    return MediaFromJSONTyped(json, false);
}

export function MediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Media {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'uRI': !exists(json, 'URI') ? undefined : json['URI'],
        'version': !exists(json, 'version') ? undefined : ((json['version'] as Array<any>).map(MediaVersionFromJSON)),
    };
}

export function MediaToJSON(value?: Media | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'URI': value.uRI,
        'version': value.version === undefined ? undefined : ((value.version as Array<any>).map(MediaVersionToJSON)),
    };
}

