/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyInfo } from './CurrencyInfo';
import { HttpFile } from '../http/http';

export class NFTTransactionLogLine {
    'price'?: CurrencyInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "CurrencyInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NFTTransactionLogLine.attributeTypeMap;
    }

    public constructor() {
    }
}

