/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NFTTransactionLogLine } from './NFTTransactionLogLine';
import { HttpFile } from '../http/http';

export class NFTTransaction {
    'fromAddress'?: string;
    /**
    * Deprecated: do not use. Use `nft.lastSoldPrice` instead.
    */
    'logLine'?: Array<NFTTransactionLogLine>;
    /**
    * Timestamp of the transaction in RFC 3339.
    */
    'timestamp'?: Date;
    'toAddress'?: string;
    /**
    * TransactionHash for this transaction.
    */
    'transactionHash'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "logLine",
            "baseName": "logLine",
            "type": "Array<NFTTransactionLogLine>",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionHash",
            "baseName": "transactionHash",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NFTTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}

