/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OpenSeaContract {
    'assetContractType'?: OpenSeaContractAssetContractTypeEnum;
    /**
    * Total fee levied on buyers by this contract, in basis points
    */
    'buyerFeeBasisPoints'?: number;
    'defaultToFiat'?: boolean;
    /**
    * The NFT Version
    */
    'nftVersion'?: string;
    /**
    * The OpenSea Version
    */
    'openSeaVersion'?: string;
    /**
    * Total fee levied on sellers by this contract, in basis points
    */
    'sellerFeeBasisPoints'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetContractType",
            "baseName": "assetContractType",
            "type": "OpenSeaContractAssetContractTypeEnum",
            "format": ""
        },
        {
            "name": "buyerFeeBasisPoints",
            "baseName": "buyerFeeBasisPoints",
            "type": "number",
            "format": ""
        },
        {
            "name": "defaultToFiat",
            "baseName": "defaultToFiat",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nftVersion",
            "baseName": "nftVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "openSeaVersion",
            "baseName": "openSeaVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "sellerFeeBasisPoints",
            "baseName": "sellerFeeBasisPoints",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OpenSeaContract.attributeTypeMap;
    }

    public constructor() {
    }
}


export type OpenSeaContractAssetContractTypeEnum = "NFT" | "SFT" | "unknown" ;

