/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Collection } from './Collection';
import { CurrencyInfo } from './CurrencyInfo';
import { Token } from './Token';
import { HttpFile } from '../http/http';

export class OwnedCollection {
    'collection'?: Collection;
    /**
    * A sample of the tokens owned by this wallet.
    */
    'tokens'?: Array<Token>;
    /**
    * Total number of tokens in this collection owned by a wallet.
    */
    'totalOwnedTokens'?: number;
    'totalSpent'?: CurrencyInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collection",
            "baseName": "collection",
            "type": "Collection",
            "format": ""
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<Token>",
            "format": ""
        },
        {
            "name": "totalOwnedTokens",
            "baseName": "totalOwnedTokens",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalSpent",
            "baseName": "totalSpent",
            "type": "CurrencyInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OwnedCollection.attributeTypeMap;
    }

    public constructor() {
    }
}

