/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Collection } from './Collection';
import { Token } from './Token';
import { Wallet } from './Wallet';
import { HttpFile } from '../http/http';

export class SearchDocument {
    'collection'?: Collection;
    'token'?: Token;
    'wallet'?: Wallet;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collection",
            "baseName": "collection",
            "type": "Collection",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "Token",
            "format": ""
        },
        {
            "name": "wallet",
            "baseName": "wallet",
            "type": "Wallet",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchDocument.attributeTypeMap;
    }

    public constructor() {
    }
}

