/* tslint:disable */
/* eslint-disable */
/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * The version of the OpenAPI document: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialMedia
 */
export interface SocialMedia {
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    network?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    username?: string;
}

/**
 * Check if a given object implements the SocialMedia interface.
 */
export function instanceOfSocialMedia(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SocialMediaFromJSON(json: any): SocialMedia {
    return SocialMediaFromJSONTyped(json, false);
}

export function SocialMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialMedia {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': !exists(json, 'network') ? undefined : json['network'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function SocialMediaToJSON(value?: SocialMedia | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'username': value.username,
    };
}

