/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.18.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockchainInfo } from './BlockchainInfo';
import { NonFungibleToken } from './NonFungibleToken';
import { OpenSeaContract } from './OpenSeaContract';
import { HttpFile } from '../http/http';

export class Token {
    'blockchain': BlockchainInfo;
    /**
    * Address of the contract that minted this NFT.
    */
    'contractAddress': string;
    'nft'?: NonFungibleToken;
    'openSeaContract'?: OpenSeaContract;
    'symbol'?: string;
    'tokenStandard'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockchain",
            "baseName": "blockchain",
            "type": "BlockchainInfo",
            "format": ""
        },
        {
            "name": "contractAddress",
            "baseName": "contractAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "nft",
            "baseName": "nft",
            "type": "NonFungibleToken",
            "format": ""
        },
        {
            "name": "openSeaContract",
            "baseName": "openSeaContract",
            "type": "OpenSeaContract",
            "format": ""
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenStandard",
            "baseName": "tokenStandard",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Token.attributeTypeMap;
    }

    public constructor() {
    }
}

