/* tslint:disable */
/* eslint-disable */
/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * The version of the OpenAPI document: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenGate
 */
export interface TokenGate {
    /**
     * 
     * @type {boolean}
     * @memberof TokenGate
     */
    hasToken: boolean;
}

/**
 * Check if a given object implements the TokenGate interface.
 */
export function instanceOfTokenGate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasToken" in value;

    return isInstance;
}

export function TokenGateFromJSON(json: any): TokenGate {
    return TokenGateFromJSONTyped(json, false);
}

export function TokenGateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenGate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasToken': json['hasToken'],
    };
}

export function TokenGateToJSON(value?: TokenGate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasToken': value.hasToken,
    };
}

