/* tslint:disable */
/* eslint-disable */
/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * The version of the OpenAPI document: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenAttribute
 */
export interface TokenAttribute {
    /**
     * The key or kind of trait.
     * @type {string}
     * @memberof TokenAttribute
     */
    traitType?: string;
    /**
     * A distinct attribute belonging to a particular type of trait.
     * @type {string}
     * @memberof TokenAttribute
     */
    value?: string;
}

/**
 * Check if a given object implements the TokenAttribute interface.
 */
export function instanceOfTokenAttribute(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenAttributeFromJSON(json: any): TokenAttribute {
    return TokenAttributeFromJSONTyped(json, false);
}

export function TokenAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenAttribute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'traitType': !exists(json, 'traitType') ? undefined : json['traitType'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function TokenAttributeToJSON(value?: TokenAttribute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'traitType': value.traitType,
        'value': value.value,
    };
}

