/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.18.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TokenGate {
    'hasToken': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasToken",
            "baseName": "hasToken",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TokenGate.attributeTypeMap;
    }

    public constructor() {
    }
}

