/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyInfo } from './CurrencyInfo';
import { TransactionLogLine } from './TransactionLogLine';
import { HttpFile } from '../http/http';

export class Transaction {
    /**
    * Block number of the transaction.
    */
    'blockNumber'?: number;
    'gasFee'?: CurrencyInfo;
    /**
    * Log lines related to the transaction.
    */
    'logLine'?: Array<TransactionLogLine>;
    /**
    * Timestamp of the transaction in RFC 3339.
    */
    'timestamp'?: Date;
    /**
    * A token ID if the transaction was related to an NFT
    */
    'tokenID'?: string;
    /**
    * TransactionHash for this transaction.
    */
    'transactionHash'?: string;
    /**
    * Index of the transaction in the block.
    */
    'transactionIndex'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockNumber",
            "baseName": "blockNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "gasFee",
            "baseName": "gasFee",
            "type": "CurrencyInfo",
            "format": ""
        },
        {
            "name": "logLine",
            "baseName": "logLine",
            "type": "Array<TransactionLogLine>",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "tokenID",
            "baseName": "tokenID",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionHash",
            "baseName": "transactionHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionIndex",
            "baseName": "transactionIndex",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }

    public constructor() {
    }
}

