/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.17.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyInfo } from './CurrencyInfo';
import { HttpFile } from '../http/http';

export class TransactionLogLine {
    /**
    * When the value is true, it indicates that a token has been burned, and this transaction corresponds to the burn.
    */
    'burned'?: boolean;
    /**
    * When the value is true, it indicates this is the transaction representing a token minting.
    */
    'mint'?: boolean;
    /**
    * Index of the log in the transaction.
    */
    'logIndex'?: number;
    'fromAddress'?: string;
    'toAddress'?: string;
    'price'?: CurrencyInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "burned",
            "baseName": "burned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mint",
            "baseName": "mint",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "logIndex",
            "baseName": "logIndex",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "CurrencyInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionLogLine.attributeTypeMap;
    }

    public constructor() {
    }
}

