/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransactionLogLine {
    /**
    * When the value is true, it indicates that a token has been burned, and this transaction corresponds to the burn.
    */
    'burned'?: boolean;
    /**
    * Contract topic0 signature related to the log line.
    */
    'eventName'?: string;
    /**
    * Protocol contract address that generated the given log entry.
    */
    'logAddress'?: string;
    /**
    * Protocol name that generated the given log entry.
    */
    'logAddressProtocol'?: string;
    /**
    * Raw hex data from contract call.
    */
    'logData'?: string;
    /**
    * Index of the log in the transaction.
    */
    'logIndex'?: number;
    /**
    * Topic signatures.
    */
    'logTopics'?: Array<string>;
    /**
    * When the value is true, it indicates this is the transaction representing a token minting.
    */
    'mint'?: boolean;
    /**
    * Transaction index of the log in the transaction.
    */
    'transactionIndex'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "burned",
            "baseName": "burned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "eventName",
            "baseName": "eventName",
            "type": "string",
            "format": ""
        },
        {
            "name": "logAddress",
            "baseName": "logAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "logAddressProtocol",
            "baseName": "logAddressProtocol",
            "type": "string",
            "format": ""
        },
        {
            "name": "logData",
            "baseName": "logData",
            "type": "string",
            "format": ""
        },
        {
            "name": "logIndex",
            "baseName": "logIndex",
            "type": "number",
            "format": ""
        },
        {
            "name": "logTopics",
            "baseName": "logTopics",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mint",
            "baseName": "mint",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "transactionIndex",
            "baseName": "transactionIndex",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionLogLine.attributeTypeMap;
    }

    public constructor() {
    }
}

