/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyInfo } from './CurrencyInfo';
import { TransactionLogLine } from './TransactionLogLine';
import { HttpFile } from '../http/http';

export class Transaction {
    /**
    * Block number of the transaction.
    */
    'blockNumber'?: number;
    'fromAddress'?: string;
    /**
    * Amount of gas used
    */
    'gas'?: number;
    'gasFee'?: CurrencyInfo;
    /**
    * Log lines related to the transaction.
    */
    'logLine'?: Array<TransactionLogLine>;
    /**
    * The wallet or contract address allowed to spend the approved amount of tokens
    */
    'spenderAddress'?: string;
    /**
    * Timestamp of the transaction in RFC 3339.
    */
    'timestamp'?: Date;
    'toAddress'?: string;
    /**
    * A token ID if the transaction was related to an NFT.
    */
    'tokenID'?: string;
    /**
    * TransactionHash for this transaction.
    */
    'transactionHash'?: string;
    /**
    * Index of the transaction in the block.
    */
    'transactionIndex'?: number;
    'value'?: CurrencyInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockNumber",
            "baseName": "blockNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "gas",
            "baseName": "gas",
            "type": "number",
            "format": ""
        },
        {
            "name": "gasFee",
            "baseName": "gasFee",
            "type": "CurrencyInfo",
            "format": ""
        },
        {
            "name": "logLine",
            "baseName": "logLine",
            "type": "Array<TransactionLogLine>",
            "format": ""
        },
        {
            "name": "spenderAddress",
            "baseName": "spenderAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenID",
            "baseName": "tokenID",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionHash",
            "baseName": "transactionHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionIndex",
            "baseName": "transactionIndex",
            "type": "number",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "CurrencyInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }

    public constructor() {
    }
}

