/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * neeva.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.0.9
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface Collection
 */
export interface Collection {
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    blockchain: string;
    /**
     * Address of the contract that minted this NFT
     * @type {string}
     * @memberof Collection
     */
    contractAddress: string;
    /**
     * A sample of the tokens minted by this collection
     * @type {Array<Token>}
     * @memberof Collection
     */
    tokens?: Array<Token>;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    symbol?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    shortDescription?: string;
    /**
     * Timestamp of creation of this contract in RFC 3339.
     * @type {Date}
     * @memberof Collection
     */
    createdDate?: Date;
    /**
     * 
     * @type {Media}
     * @memberof Collection
     */
    bannerImage?: Media;
    /**
     * 
     * @type {Media}
     * @memberof Collection
     */
    featuredImage?: Media;
    /**
     * 
     * @type {Array<URL>}
     * @memberof Collection
     */
    urls?: Array<URL>;
    /**
     * 
     * @type {Array<SocialMedia>}
     * @memberof Collection
     */
    socialMedia?: Array<SocialMedia>;
}
/**
 * 
 * @export
 * @interface CurrencyInfo
 */
export interface CurrencyInfo {
    /**
     * Transaction value as a string-encoded bigint in the base unit for a given blockchain (e.g. wei for Ethereum) or fiat currency (e.g. US Dollars).
     * @type {string}
     * @memberof CurrencyInfo
     */
    value?: string;
    /**
     * A formatted, human-friendly representation of the transaction value, e.g. the value in Ether, possibly with localized thousands separator and radix character.
     * @type {string}
     * @memberof CurrencyInfo
     */
    pretty?: string;
    /**
     * 10^decimals = 1 unit, e.g. 10^18 = 1 ETH
     * @type {number}
     * @memberof CurrencyInfo
     */
    decimals?: number;
    /**
     * Abbreviation commonly used to describe a blockchain
     * @type {string}
     * @memberof CurrencyInfo
     */
    symbol?: string;
    /**
     * Name for one unit of a cryptocurrency
     * @type {string}
     * @memberof CurrencyInfo
     */
    name?: string;
    /**
     * A list of the given value in a fiat currency, e.g. USD.
     * @type {Array<CurrencyInfo>}
     * @memberof CurrencyInfo
     */
    spotPrices?: Array<CurrencyInfo>;
}
/**
 * 
 * @export
 * @interface ENS
 */
export interface ENS {
    /**
     * The ENS or domain name
     * @type {string}
     * @memberof ENS
     */
    name?: string;
    /**
     * The address the ENS record points to
     * @type {string}
     * @memberof ENS
     */
    pointsTo?: string;
    /**
     * Date the ENS registration explires
     * @type {Date}
     * @memberof ENS
     */
    expires?: Date;
    /**
     * A wallet address can have multiple ENS names. The primary ENS name represents a \"cross-platform web3 username and profile.\" A wallet address can only have one primary name, and it can change at any time.
     * @type {boolean}
     * @memberof ENS
     */
    isPrimary?: boolean;
}
/**
 * 
 * @export
 * @interface ErrorMessage
 */
export interface ErrorMessage {
    /**
     * 
     * @type {string}
     * @memberof ErrorMessage
     */
    error: string;
}
/**
 * 
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    key: string;
    /**
     * URI for the image asset
     * @type {string}
     * @memberof Media
     */
    URI?: string;
    /**
     * 
     * @type {Array<MediaVersion>}
     * @memberof Media
     */
    version?: Array<MediaVersion>;
}
/**
 * 
 * @export
 * @interface MediaVersion
 */
export interface MediaVersion {
    /**
     * 
     * @type {string}
     * @memberof MediaVersion
     */
    kind?: MediaVersion.KindEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaVersion
     */
    format?: string;
    /**
     * 
     * @type {number}
     * @memberof MediaVersion
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof MediaVersion
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof MediaVersion
     */
    numBytes?: number;
    /**
     * If a video, length of video in ISO 8601 duration format.
     * @type {string}
     * @memberof MediaVersion
     */
    duration?: string;
}

/**
 * @export
 * @namespace MediaVersion
 */
export namespace MediaVersion {
    /**
     * @export
     * @enum {string}
     */
    export enum KindEnum {
        Video = <any> 'video',
        Image = <any> 'image',
        Raw = <any> 'raw',
        Audio = <any> 'audio'
    }
}
/**
 * 
 * @export
 * @interface OwnedCollection
 */
export interface OwnedCollection {
    /**
     * A sample of the tokens owned by this wallet
     * @type {Array<Token>}
     * @memberof OwnedCollection
     */
    tokens?: Array<Token>;
    /**
     * 
     * @type {Collection}
     * @memberof OwnedCollection
     */
    collection?: Collection;
    /**
     * 
     * @type {CurrencyInfo}
     * @memberof OwnedCollection
     */
    totalSpent?: CurrencyInfo;
}
/**
 * 
 * @export
 * @interface SocialMedia
 */
export interface SocialMedia {
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    network?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    username?: string;
}
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    blockchain: string;
    /**
     * Address of the contract that minted this NFT
     * @type {string}
     * @memberof Token
     */
    contractAddress: string;
    /**
     * ID of this particular token
     * @type {string}
     * @memberof Token
     */
    tokenID: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    tokenStandard?: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    contractTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    symbol?: string;
    /**
     * A description of a contract may contain markup such as HTML or Markdown
     * @type {string}
     * @memberof Token
     */
    description?: string;
    /**
     * 
     * @type {Media}
     * @memberof Token
     */
    media?: Media;
    /**
     * 
     * @type {Wallet}
     * @memberof Token
     */
    owner?: Wallet;
    /**
     * 
     * @type {Array<TokenAttribute>}
     * @memberof Token
     */
    attributes?: Array<TokenAttribute>;
    /**
     * 
     * @type {Collection}
     * @memberof Token
     */
    collection?: Collection;
    /**
     * 
     * @type {Transaction}
     * @memberof Token
     */
    purchase?: Transaction;
    /**
     * A rough heuristic indicating the underlying technology and hypothetical durability of an asset. \"On-Chain\" assets store metadata and the asset media (e.g. SVG file, source code or MIDI) on a blockchain. \"Distributed\" assets are stored on decentralized protocols such as IPFS. \"Web\" assets are stored on services such as Amazon's S3. Each technology has different tradeoffs, in particular certain projects need more flexibility than is provided by on-chain data.\"
     * @type {string}
     * @memberof Token
     */
    durability?: Token.DurabilityEnum;
}

/**
 * @export
 * @namespace Token
 */
export namespace Token {
    /**
     * @export
     * @enum {string}
     */
    export enum DurabilityEnum {
        OnChain = <any> 'On-Chain',
        Decentralized = <any> 'Decentralized',
        Web = <any> 'Web',
        Unknown = <any> 'Unknown'
    }
}
/**
 * 
 * @export
 * @interface TokenAttribute
 */
export interface TokenAttribute {
    /**
     * The key or kind of trait
     * @type {string}
     * @memberof TokenAttribute
     */
    traitType?: string;
    /**
     * A distinct attribute belonging to a particular type of trait
     * @type {string}
     * @memberof TokenAttribute
     */
    value?: string;
}
/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    fromAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    toAddress?: string;
    /**
     * Timestamp of last transaction for this token in RFC 3339.
     * @type {Date}
     * @memberof Transaction
     */
    timestamp?: Date;
    /**
     * 
     * @type {CurrencyInfo}
     * @memberof Transaction
     */
    price?: CurrencyInfo;
}
/**
 * 
 * @export
 * @interface URL
 */
export interface URL {
    /**
     * Human-readable name of the site, ideally simplified to a label that might appear on a business card
     * @type {string}
     * @memberof URL
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof URL
     */
    url?: string;
}
/**
 * 
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     * The total balance in a fiat currency (e.g. USD) for the wallet.
     * @type {Array<CurrencyInfo>}
     * @memberof Wallet
     */
    totalBalance?: Array<CurrencyInfo>;
    /**
     * The balance of fungible tokens from smart contracts or blockchains.
     * @type {Array<CurrencyInfo>}
     * @memberof Wallet
     */
    balances?: Array<CurrencyInfo>;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    address: string;
    /**
     * 
     * @type {Array<ENS>}
     * @memberof Wallet
     */
    ens?: Array<ENS>;
    /**
     * 
     * @type {Array<SocialMedia>}
     * @memberof Wallet
     */
    socialMedia?: Array<SocialMedia>;
    /**
     * A sample of the tokens owned by this wallet
     * @type {Array<Token>}
     * @memberof Wallet
     */
    tokens?: Array<Token>;
    /**
     * A sample of the collections this wallet owns.
     * @type {Array<OwnedCollection>}
     * @memberof Wallet
     */
    collections?: Array<OwnedCollection>;
}
/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a collection by its contract address
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1CollectionsContractAddressGet(contractAddress: string, options: any = {}): FetchArgs {
            // verify required parameter 'contractAddress' is not null or undefined
            if (contractAddress === null || contractAddress === undefined) {
                throw new RequiredError('contractAddress','Required parameter contractAddress was null or undefined when calling apiV1CollectionsContractAddressGet.');
            }
            const localVarPath = `/api/v1/collections/{contractAddress}`
                .replace(`{${"contractAddress"}}`, encodeURIComponent(String(contractAddress)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a collections
         * @param {string} [contractAddress] A hex address for a blockchain contract
         * @param {string} [query] A search query containing keywords or operators to filter tokens
         * @param {string} [sort] A means to order collections by specific values
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1CollectionsGet(contractAddress?: string, query?: string, sort?: string, options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/collections`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contractAddress !== undefined) {
                localVarQueryParameter['contractAddress'] = contractAddress;
            }

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tokens by contract address
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensContractAddressGet(contractAddress: string, options: any = {}): FetchArgs {
            // verify required parameter 'contractAddress' is not null or undefined
            if (contractAddress === null || contractAddress === undefined) {
                throw new RequiredError('contractAddress','Required parameter contractAddress was null or undefined when calling apiV1TokensContractAddressGet.');
            }
            const localVarPath = `/api/v1/tokens/{contractAddress}`
                .replace(`{${"contractAddress"}}`, encodeURIComponent(String(contractAddress)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a token by its contract address and token id
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {string} tokenID An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensContractAddressTokenIDGet(contractAddress: string, tokenID: string, options: any = {}): FetchArgs {
            // verify required parameter 'contractAddress' is not null or undefined
            if (contractAddress === null || contractAddress === undefined) {
                throw new RequiredError('contractAddress','Required parameter contractAddress was null or undefined when calling apiV1TokensContractAddressTokenIDGet.');
            }
            // verify required parameter 'tokenID' is not null or undefined
            if (tokenID === null || tokenID === undefined) {
                throw new RequiredError('tokenID','Required parameter tokenID was null or undefined when calling apiV1TokensContractAddressTokenIDGet.');
            }
            const localVarPath = `/api/v1/tokens/{contractAddress}/{tokenID}`
                .replace(`{${"contractAddress"}}`, encodeURIComponent(String(contractAddress)))
                .replace(`{${"tokenID"}}`, encodeURIComponent(String(tokenID)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tokens
         * @param {string} [contractAddress] A hex address for a blockchain contract
         * @param {string} [tokenID] An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
         * @param {string} [query] A search query containing keywords or operators to filter tokens
         * @param {string} [sort] A means to order tokens by specific values
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensGet(contractAddress?: string, tokenID?: string, query?: string, sort?: string, options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/tokens`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contractAddress !== undefined) {
                localVarQueryParameter['contractAddress'] = contractAddress;
            }

            if (tokenID !== undefined) {
                localVarQueryParameter['tokenID'] = tokenID;
            }

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a Wallet
         * @param {string} [walletAddress] A hex string referencing a public wallet address
         * @param {string} [query] A search query containing keywords or operators to filter wallets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsGet(walletAddress?: string, query?: string, options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/wallets`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletAddress !== undefined) {
                localVarQueryParameter['walletAddress'] = walletAddress;
            }

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a wallet by a wallet address
         * @param {string} walletAddress A hex string referencing a public wallet address.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsWalletAddressGet(walletAddress: string, options: any = {}): FetchArgs {
            // verify required parameter 'walletAddress' is not null or undefined
            if (walletAddress === null || walletAddress === undefined) {
                throw new RequiredError('walletAddress','Required parameter walletAddress was null or undefined when calling apiV1WalletsWalletAddressGet.');
            }
            const localVarPath = `/api/v1/wallets/{walletAddress}`
                .replace(`{${"walletAddress"}}`, encodeURIComponent(String(walletAddress)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a collection by its contract address
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1CollectionsContractAddressGet(contractAddress: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Collection>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1CollectionsContractAddressGet(contractAddress, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get a collections
         * @param {string} [contractAddress] A hex address for a blockchain contract
         * @param {string} [query] A search query containing keywords or operators to filter tokens
         * @param {string} [sort] A means to order collections by specific values
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1CollectionsGet(contractAddress?: string, query?: string, sort?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Collection>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1CollectionsGet(contractAddress, query, sort, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get tokens by contract address
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensContractAddressGet(contractAddress: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Token>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1TokensContractAddressGet(contractAddress, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get a token by its contract address and token id
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {string} tokenID An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensContractAddressTokenIDGet(contractAddress: string, tokenID: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Token> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1TokensContractAddressTokenIDGet(contractAddress, tokenID, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get tokens
         * @param {string} [contractAddress] A hex address for a blockchain contract
         * @param {string} [tokenID] An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
         * @param {string} [query] A search query containing keywords or operators to filter tokens
         * @param {string} [sort] A means to order tokens by specific values
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensGet(contractAddress?: string, tokenID?: string, query?: string, sort?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Token>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1TokensGet(contractAddress, tokenID, query, sort, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get a Wallet
         * @param {string} [walletAddress] A hex string referencing a public wallet address
         * @param {string} [query] A search query containing keywords or operators to filter wallets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsGet(walletAddress?: string, query?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Wallet>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1WalletsGet(walletAddress, query, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get a wallet by a wallet address
         * @param {string} walletAddress A hex string referencing a public wallet address.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsWalletAddressGet(walletAddress: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Wallet>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV1WalletsWalletAddressGet(walletAddress, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Get a collection by its contract address
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1CollectionsContractAddressGet(contractAddress: string, options?: any) {
            return DefaultApiFp(configuration).apiV1CollectionsContractAddressGet(contractAddress, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get a collections
         * @param {string} [contractAddress] A hex address for a blockchain contract
         * @param {string} [query] A search query containing keywords or operators to filter tokens
         * @param {string} [sort] A means to order collections by specific values
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1CollectionsGet(contractAddress?: string, query?: string, sort?: string, options?: any) {
            return DefaultApiFp(configuration).apiV1CollectionsGet(contractAddress, query, sort, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get tokens by contract address
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensContractAddressGet(contractAddress: string, options?: any) {
            return DefaultApiFp(configuration).apiV1TokensContractAddressGet(contractAddress, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get a token by its contract address and token id
         * @param {string} contractAddress A hex address for a blockchain contract
         * @param {string} tokenID An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensContractAddressTokenIDGet(contractAddress: string, tokenID: string, options?: any) {
            return DefaultApiFp(configuration).apiV1TokensContractAddressTokenIDGet(contractAddress, tokenID, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get tokens
         * @param {string} [contractAddress] A hex address for a blockchain contract
         * @param {string} [tokenID] An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
         * @param {string} [query] A search query containing keywords or operators to filter tokens
         * @param {string} [sort] A means to order tokens by specific values
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokensGet(contractAddress?: string, tokenID?: string, query?: string, sort?: string, options?: any) {
            return DefaultApiFp(configuration).apiV1TokensGet(contractAddress, tokenID, query, sort, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get a Wallet
         * @param {string} [walletAddress] A hex string referencing a public wallet address
         * @param {string} [query] A search query containing keywords or operators to filter wallets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsGet(walletAddress?: string, query?: string, options?: any) {
            return DefaultApiFp(configuration).apiV1WalletsGet(walletAddress, query, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get a wallet by a wallet address
         * @param {string} walletAddress A hex string referencing a public wallet address.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsWalletAddressGet(walletAddress: string, options?: any) {
            return DefaultApiFp(configuration).apiV1WalletsWalletAddressGet(walletAddress, options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get a collection by its contract address
     * @param {string} contractAddress A hex address for a blockchain contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1CollectionsContractAddressGet(contractAddress: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1CollectionsContractAddressGet(contractAddress, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get a collections
     * @param {string} [contractAddress] A hex address for a blockchain contract
     * @param {string} [query] A search query containing keywords or operators to filter tokens
     * @param {string} [sort] A means to order collections by specific values
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1CollectionsGet(contractAddress?: string, query?: string, sort?: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1CollectionsGet(contractAddress, query, sort, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get tokens by contract address
     * @param {string} contractAddress A hex address for a blockchain contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1TokensContractAddressGet(contractAddress: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1TokensContractAddressGet(contractAddress, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get a token by its contract address and token id
     * @param {string} contractAddress A hex address for a blockchain contract
     * @param {string} tokenID An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1TokensContractAddressTokenIDGet(contractAddress: string, tokenID: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1TokensContractAddressTokenIDGet(contractAddress, tokenID, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get tokens
     * @param {string} [contractAddress] A hex address for a blockchain contract
     * @param {string} [tokenID] An arbitrary ID defined by a contract to uniquely identify a cryptographic asset such as an NFT
     * @param {string} [query] A search query containing keywords or operators to filter tokens
     * @param {string} [sort] A means to order tokens by specific values
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1TokensGet(contractAddress?: string, tokenID?: string, query?: string, sort?: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1TokensGet(contractAddress, tokenID, query, sort, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get a Wallet
     * @param {string} [walletAddress] A hex string referencing a public wallet address
     * @param {string} [query] A search query containing keywords or operators to filter wallets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1WalletsGet(walletAddress?: string, query?: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1WalletsGet(walletAddress, query, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get a wallet by a wallet address
     * @param {string} walletAddress A hex string referencing a public wallet address.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV1WalletsWalletAddressGet(walletAddress: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV1WalletsWalletAddressGet(walletAddress, options)(this.fetch, this.basePath);
    }

}
