/**
 * n.xyz REST API
 * REST API for blockchain data.
 *
 * OpenAPI spec version: 0.7.0
 * Contact: joshua@n.xyz
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("apiV1BlockchainsGet", () => {
    return expect(instance.apiV1BlockchainsGet({})).resolves.toBe(null)
  })
  test("apiV1CollectionsContractAddressGet", () => {
    const contractAddress: string = "contractAddress_example"
    const chainID: string = "chainID_example"
    return expect(instance.apiV1CollectionsContractAddressGet(contractAddress, chainID, {})).resolves.toBe(null)
  })
  test("apiV1TokensContractAddressGet", () => {
    const contractAddress: string = "contractAddress_example"
    const chainID: string = "chainID_example"
    const page: number = 1.2
    const limit: number = 1.2
    return expect(instance.apiV1TokensContractAddressGet(contractAddress, chainID, page, limit, {})).resolves.toBe(null)
  })
  test("apiV1TokensContractAddressTokenIDGet", () => {
    const contractAddress: string = "contractAddress_example"
    const tokenID: string = "tokenID_example"
    const chainID: string = "chainID_example"
    return expect(instance.apiV1TokensContractAddressTokenIDGet(contractAddress, tokenID, chainID, {})).resolves.toBe(null)
  })
  test("apiV1WalletsWalletAddressGet", () => {
    const walletAddress: string = "walletAddress_example"
    const chainID: string = "chainID_example"
    return expect(instance.apiV1WalletsWalletAddressGet(walletAddress, chainID, {})).resolves.toBe(null)
  })
})

